spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true



jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 1800000
  refresh-token-expiration: 1209600000

auth:
  allowed-origins: http://localhost:5173
  refresh-cookie-secure: false
  refresh-cookie-same-site: Lax

provider:
  api-key-password: ${PROVIDER_API_KEY_PASSWORD}
  api-key-salt: ${PROVIDER_API_KEY_SALT}
