export const executionPageStyles = {
  main: { maxWidth: '1180px', margin: '36px auto', padding: '0 24px 56px' },
  hero: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    gap: '28px',
    padding: '30px 32px',
    marginBottom: '24px',
    borderRadius: '8px',
    background: 'var(--pd-primary-gradient)',
    color: 'var(--pd-on-primary)',
    boxShadow: 'var(--pd-glow)',
    border: '1px solid var(--pd-border-soft)'
  },
  eyebrow: { fontSize: '12px', fontWeight: 900, textTransform: 'uppercase', opacity: 0.82, marginBottom: '8px' },
  heroTitle: { fontSize: '40px', fontWeight: 900, margin: 0, letterSpacing: 0 },
  heroDesc: { maxWidth: '640px', marginTop: '8px', lineHeight: 1.7, fontSize: '14px', opacity: 0.9 },
  heroStats: { display: 'flex', gap: '10px', flexWrap: 'wrap', justifyContent: 'flex-end' },
  heroStat: {
    minWidth: '92px',
    padding: '12px 14px',
    borderRadius: '8px',
    background: 'rgba(255,255,255,0.16)',
    border: '1px solid rgba(255,255,255,0.34)',
    backdropFilter: 'blur(12px)',
    display: 'flex',
    flexDirection: 'column',
    gap: '2px'
  },
  panelHeader: { display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', gap: '12px', marginBottom: '8px' },
  panelKicker: { color: 'var(--pd-accent)', fontSize: '11px', fontWeight: 900, textTransform: 'uppercase' },
  subheading: { fontSize: '18px', fontWeight: 800, margin: 0, color: 'var(--pd-heading)' },
  layout: { display: 'grid', gridTemplateColumns: 'minmax(0, 1.05fr) minmax(0, 0.95fr)', gap: '24px', alignItems: 'start' },
  panel: { background: 'var(--pd-surface-raised)', borderRadius: '8px', border: '1px solid var(--pd-border-soft)', padding: '24px', boxShadow: 'var(--pd-shadow-sm)', display: 'flex', flexDirection: 'column', gap: '12px' },
  label: { fontSize: '13px', fontWeight: 600, color: 'var(--pd-text)' },
  hint: { fontWeight: 400, color: 'var(--pd-muted-soft)' },
  select: { padding: '10px 12px', border: '1px solid var(--pd-border)', borderRadius: '8px', fontSize: '14px', outline: 'none' },
  input: { padding: '10px 12px', border: '1px solid var(--pd-border)', borderRadius: '8px', fontSize: '14px', outline: 'none' },
  textarea: { padding: '12px 14px', border: '1px solid var(--pd-border)', borderRadius: '8px', fontSize: '13px', fontFamily: 'inherit', outline: 'none', resize: 'vertical' },
  optionSection: { border: '1px solid var(--pd-border-soft)', borderRadius: '8px', padding: '14px', background: 'var(--pd-surface-muted)' },
  optionTitle: { fontSize: '13px', fontWeight: 700, marginBottom: '10px' },
  optionGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '10px' },
  optionField: { display: 'flex', flexDirection: 'column', gap: '5px' },
  optionLabelRow: { display: 'flex', justifyContent: 'space-between', gap: '8px', alignItems: 'center', fontSize: '12px', fontWeight: 600, color: 'var(--pd-text)' },
  optionRange: { color: 'var(--pd-muted-soft)', fontWeight: 500 },
  rangeField: { display: 'grid', gridTemplateColumns: '1fr 72px', gap: '8px', alignItems: 'center' },
  range: { width: '100%' },
  rangeNumber: { width: '72px', boxSizing: 'border-box', padding: '8px 6px', border: '1px solid var(--pd-border)', borderRadius: '6px', fontSize: '13px', outline: 'none' },
  settingInfo: { background: 'var(--pd-surface-muted)', borderRadius: '8px', padding: '12px', border: '1px solid var(--pd-border-soft)' },
  settingInfoRow: { fontSize: '12px', color: 'var(--pd-text)', marginBottom: '4px' },
  btnRow: { display: 'flex', gap: '10px', marginTop: '4px' },
  presetPanel: { border: '1px solid var(--pd-border-soft)', borderRadius: '8px', padding: '12px', background: 'var(--pd-surface-muted)', display: 'flex', flexDirection: 'column', gap: '8px' },
  presetRow: { display: 'grid', gridTemplateColumns: '1fr auto auto', gap: '8px', alignItems: 'center' },
  presetEditor: { borderTop: '1px solid var(--pd-border-soft)', paddingTop: '8px', display: 'flex', flexDirection: 'column', gap: '8px' },
  presetEditorRow: { display: 'grid', gridTemplateColumns: '1fr auto', gap: '8px', alignItems: 'center' },
  presetEditorActions: { display: 'flex', gap: '8px', justifyContent: 'flex-end', flexWrap: 'wrap' },
  presetMeta: { margin: 0, color: 'var(--pd-muted)', fontSize: '12px' },
  disclosure: { alignSelf: 'flex-start', background: 'transparent', border: 'none', color: 'var(--pd-primary)', padding: '2px 0', fontSize: '13px', fontWeight: 600, cursor: 'pointer' },
  info: { color: 'var(--pd-muted)', fontSize: '14px' },
  warn: { color: 'var(--pd-warning)', fontSize: '13px', background: 'var(--pd-warning-soft)', padding: '10px', borderRadius: '6px', border: '1px solid var(--pd-warning)' },
  error: { color: 'var(--pd-danger)', fontSize: '13px' },
  confirmText: { color: 'var(--pd-text)', fontSize: '14px', lineHeight: 1.6 },
  resultLabel: { fontSize: '15px', fontWeight: 700, marginBottom: '10px' },
  resultHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '6px' },
  resultMeta: { display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '12px' },
  endpoint: { fontSize: '12px', color: 'var(--pd-text)', background: 'var(--pd-surface-muted)', padding: '6px 9px', borderRadius: '8px', wordBreak: 'break-all', border: '1px solid var(--pd-border-soft)' },
  sectionLabel: { fontSize: '12px', fontWeight: 600, color: 'var(--pd-muted)', marginBottom: '4px', marginTop: '10px' },
  pre: { background: 'var(--pd-code-bg)', color: 'var(--pd-code-text)', borderRadius: '8px', padding: '14px', fontSize: '12px', fontFamily: 'monospace', overflowX: 'auto', whiteSpace: 'pre-wrap', wordBreak: 'break-all' },
  parsedBox: { background: 'var(--pd-success-soft)', border: '1px solid var(--pd-success)', borderRadius: '8px', padding: '14px', fontSize: '14px', lineHeight: 1.7, whiteSpace: 'pre-wrap', wordBreak: 'break-word' }
}
